### ISSUE TITLE
Add ShouldBeLike

### ISSUE THREAD

**Issue by lanwin** [machine/machine.specifications#103]
Simple example

foo.ShouldBeLike(new{
  Id=123,
  Name="foobar"
});

This does not use Equals for check. Instead it checks each property with reflection. This way its very easy to check multiple properties of an object without having an instance of that object before and without having to impl Equals for each object.

**Comment by derekgreer** [comment]
I wish I had seen this.  I would have pointed you to https://github.com/derekgreer/expectedObjects.
