### ISSUE TITLE
Get machine.specification working on "Metro"/AppStore apps

### ISSUE THREAD

**Issue by haf** [machine/machine.specifications#120]
```
PM> install-package machine.specifications
Successfully installed 'Machine.Specifications 0.5.9'.
Successfully uninstalled 'Machine.Specifications 0.5.9'.
Install failed. Rolling back...
install-package : Could not install package 'Machine.Specifications 0.5.9'. You are trying to install this package into a project that targets '.NETCore,Version=v4.5', but the package does not contain any assembly references or content files that are compatib
le with that framework. For more information, contact the package author.
At line:1 char:1
+ install-package machine.specifications
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
```

Unfortunately it doesn't work, and I'm going slowly insane with withdrawal symptoms from not using Machine Specifications; excessive salivation, yelling at co-workers, bitter tweets about WinRT, you name it.

I belive it's mostly a matter of compiling it for ".Net" (Windows Runtime) 4.5 and avoiding things that are dangerous according to WinRT propaganda, such as `ThreadPool` and the like.

**Comment by ivanz** [comment]
I am going to close this issue:

 * When my .NET Standard pull requests lands - UWP will be supported by "Machine.Specification"
    * I've created a "Controller" which uses the same XML protocol used by the current AppDomain remoting stuff (wich is also not something supported on .NET Core or .Net Standard), but over Action<string> for the listener and reflection over a simple interface (it's what xunit and nunit do as well). I have also added test discovery to the interface.
   * I have also eliminated the Assembly.Load(path) which are not available on the above platforms also
* What would be left is to add support to "dotnet-test-mspec" to run tests in the UWP runtime (currently it can do .NET and .NET Core): #302
