### ISSUE TITLE
Exceptions in Cleanup clause are silently ignored

### ISSUE THREAD

**Issue by benjamin-hodgson** [machine/machine.specifications#170]
If the `Establish`, `Because` and `It` statements all succeed but an exception gets raised in the `Cleanup` statement, the tests are still marked as passing.

I want to know when something's gone wrong in my `Cleanup`. It may mean that one of the assumptions of my test is wrong, or it may mean that (for example) my database has been left in an invalid state. Either way, I currently have no way of knowing.

I'd like an error during the `Cleanup` to mark the whole context as failed, like an error in the `Establish` or `Because` would.

Example:
```C#
class When_adding_two_numbers
{
    int a;
    int b;
    int result;
    Establish ctx = () =>
    {
        a = 1;
        b = 2;
    };
    Because we_add_the_numbers = () => result = a + b;
    It should_give_the_right_answer = () => result.ShouldEqual(3);
    Cleanup throws_an_exception = () =>
    {
        throw new Exception();  // this is ignored
    };
}
```

**Comment by BrunoJuchli** [comment]
i wanted to start working on this. However, i fail to run the test in Visual Studio (2013 Update 4) / ReSharper Runner (R# 8.2.2).
Of course it's fully expected that some of the examples fail. However, with the tests in .net 3.5 assemblies which rely on `FluentAssertions` I get the following exception: 

> System.BadImageFormatExceptionCould not load file or assembly 'FluentAssertions, Version=2.2.0.0, Culture=neutral, PublicKeyToken=33f2691a05b67b6a' or one of its dependencies. This assembly is built by a runtime newer than the currently loaded runtime and cannot be loaded.

It's the case for these assemblies:
 - Example.CustomDelegates
 - Example.WithBehavior
 - Example
 - Machine.Specifications.Specs
 - Machine.Specifactions.Tests

They contain a nuget packages.conf line "referencing" FluentAssertions:

    <package id="FluentAssertions" version="2.2.0.0" targetFramework="net35" />

And the downloaded nuget package for FluentAssertions actually contains a `lib\net35` folder with the corresponding files.
Can you give me any pointers?
