### ISSUE TITLE
Remove the distinction between the mspec-clr4.exe and mspec.exe

### ISSUE THREAD

**Issue by forki** [machine/machine.specifications#187]
I wonder why mspec-clr4.exe exists?

There should only be a mspec.exe and it should support .NET 4.0 and 2.0. This should be possible, right?

/cc @janekf

**Comment by ajj3085** [comment]
Supporting both with one executable means you're limited to what you can do in .Net 2.0.  Taking this further, wouldn't that mean that in .Net 4.5+ async / await would be ruled out?
