### ISSUE TITLE
Base contexts don't get picked up in R# Naming Rules

### ISSUE THREAD

**Issue by nmosafi** [machine/machine.specifications#217]
In ReSharper (8.1) under Code Editing, C#, Naming Style, under Advanced Settings I can add a user defined naming rule and under Affected entities there are options for Machine.Specifications behaviours, context, etc.

However none of these apply to a base Context, defined like this:

```
public class BaseContext 
{
   Establish context = {};
}

public class when_something_happens : BaseContext
{
  Establish context = {};
  It = {};
}
```

In this case the first context will be flagged as an naming error and unused variable, but the second context is fine.

It seems that the presence of the It is determining whether ReSharper thinks the class is a context, it should possibly be the presence of any MSpec fields or checking the inheritance chain.

**Comment by robertcoltheart** [comment]
Consider using a project-level `dotsettings` file to fix naming style. There is no way of fixing this in code.
