### ISSUE TITLE
ArgumentOutOfRangeException when running tests

### ISSUE THREAD

**Issue by nmosafi** [machine/machine.specifications#224]
Hi

I am running MSpec 0.8.0 NuGet package and using ReSharper 8.2.  When running my tests I get a popup window in Visual Studio saying:

```
Unit Test Runner failed to run tests

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: chunkLength
   at System.Text.StringBuilder.ToString()
   at System.IO.StringWriter.ToString()
```

The same issue happens on TeamCIty which is using the mspec-clr4.exe to run the tests.  The test running stops after about 20 tests and the build still passes.

Let me know if you need any more info

Thanks
Neil

**Comment by nmosafi** [comment]
Was this ever fixed or is it impossible to fix?

**Comment by mrbedo** [comment]
I'm facing the same issue in TFS. Is there a workaround at the moment other than to not use nlog?

**Comment by mrbedo** [comment]
Is anyone looking at this? I'm facing this issue every day and have no idea how to work around it. Can anyone help?

**Comment by dannyvincent** [comment]
As per the notification above I have opened a PR with a change to address this issue

**Comment by ivanz** [comment]
Thanks for the fix @dannyvincent  . I will release 0.11.1 bugfix release in the next day or so hopefully.

**Comment by nmosafi** [comment]
Wow this has been hanging around for ages!
Very happy you've finally fixed it, thanks @dannyvincent

**Comment by telleluy** [comment]
I see that the 0.11 version available on nuget does NOT contain this fix.
Or am I missing something?

**Comment by ivanz** [comment]
Sorry folks - I haven't released 0.12 just yet. Will aim to do that tonight. Keep you posted.

**Comment by ivanz** [comment]
Bugfix v0.11.1 release is now out on NuGet! Thanks for the patience 👍

**Comment by telleluy** [comment]
Thanks for quick action! 🥇
