### ISSUE TITLE
Breaking changes Update 0.6.2 -> 0.8.2

### ISSUE THREAD

**Issue by drauch** [machine/machine.specifications#239]
The following spec throws a SpecificationException in 0.6.2 but throws an ArgumentException in 0.8.2:

```
class spec
{
    It fails = () => 5.ShouldEqual(new object());
}
```

I think this should still throw a SpecificationException - bug?

**Comment by Inspyro** [comment]
Created a follow-up issue: https://github.com/machine/machine.specifications.should/issues/8

**Comment by danielmarbach** [comment]
Do you want to take over the repo and fix it yourself?
