### ISSUE TITLE
ReSharper Test runner does not find tests

### ISSUE THREAD

**Issue by cfletcher** [machine/machine.specifications#249]
Using VS 2013 Update 3 (12.0.30723) with ReSharper 8.2.1 and M.Spec.Runner.Resharper 0.8.3 and the Machine.Specifications 0.5.16 nuget package. 
No tests are displayed, no test run icons appear when in test files although the name spaces are displayed correctly.
The MSpec Test Adapter for Visual Studio (0.1.5.0) displays and runs tests as expected.

I'm aware we're using an old version of the nuget package but I can't find any notes that say it shouldn't work.

**Comment by Nonna14** [comment]
I am also encountering same issue with VS2010 and VS2013 running R# 9.2 and installed Resharper runner via Extension Manager. The test icons are not appearing and tests are not found.  Can you please guide me how did you resolve your issue.
Thanks.
