### ISSUE TITLE
Establish executes multiple times

### ISSUE THREAD

**Issue by CodingYoshi** [machine/machine.specifications#254]
I have posted a question here https://stackoverflow.com/questions/26809460/mspec-establish-delegate

Sorry for posting this here but I could not find a discussion board.

Is this normal behavior or a bug?

**Comment by ajj3085** [comment]
I'm seeing this, but I think its due to the nesting of classes, but I think this should still be supported.  http://stackoverflow.com/questions/32010702/inheritied-establish-executed-multiple-times
