### ISSUE TITLE
True Async / Await Support

### ISSUE THREAD

**Issue by dgioulakis** [machine/machine.specifications#259]
Just a brief question as I didn't see documentation on testing async code.  Is this the correct way to do so in MSpec?

``` csharp
Because of = async () => await EventManager.Raise(_Event).Await().AsTask;
or
Because of = () => EventManager.Raise(_Event).Await();
```

If so, why was this decision made over simply detecting `Task` or `Task<T>` return types and waiting till completion before invoking `It` delegates.  I understand `void` return types make dealing with `SynchronizationContext` a pain, but the majority of the time, developers shouldn't be writing async void methods to begin with.  Is this more difficult to do than I'm alluding or is it more-so related to backwards compatibility?

It certainly feels worse not trusting the calling method (MSpec) to await.

**Comment by bebeo92** [comment]
@danielmarbach Hi, is there any update for asycn support for mspec

I cannot found any document that mention about it. Hope I can get reply from you

**Comment by danielmarbach** [comment]
Hi, I'm not involved anymore with mspec. I wasn't for a long time. Maybe someone else can comment here

**Comment by robertcoltheart** [comment]
I'm currently maintaining mspec, and it's on the plans for `2.0`, but nothing concrete yet, follow here: #293

**Comment by bebeo92** [comment]
Thanks for reply, actually later I also found that link and plan to link it into this thread
But busy with some other work stuff
Once again thanks for your comment

**Comment by mikeblakeuk** [comment]
We really would love async in our machine spec tests.
Is there a preview branch we can try? Thanks
