### ISSUE TITLE
R# Test Runner doesn't work in VS2013 / R# 8.2

### ISSUE THREAD

**Issue by pkrakowiak** [machine/machine.specifications#262]
I can't get the MSpec test runner to work with VS2013 / R# 8.2. I installed the R# extension from the ReSharper Gallery, but it's not available under Options -> Unit Testing and R# does not recognize the unit tests in my project.

![zrzut ekranu 186](https://cloud.githubusercontent.com/assets/736489/5802782/6f55a4d6-9ff8-11e4-89e5-24659b0181f4.png)

![zrzut ekranu 187](https://cloud.githubusercontent.com/assets/736489/5802784/72dae076-9ff8-11e4-9b2f-1c17edf6483e.png)

I can't run the .bat (old method) files because they are not available in NuGet packages.

**Comment by danielmarbach** [comment]
Did you try uninstall, restart, install, restart?

**Comment by pkrakowiak** [comment]
Yes, I did exactly that before posting here. I just found out I've been using an older version of R#, so I uninstalled MSpec plugin, upgraded ReSharper and installed the MSpec plugin again just now. Unfortunately it still doesn't seem to work - MSpec does not show under Tools->Unit Testing menu.

I'm running VS 2013 Update 4 and R# 8.2.3 on Windows 8.1.

**Comment by agross** [comment]
Does mspec show up under ReSharper, Options, Plugins? There is no other menu for mspec. 




Alex
-- 
Alexander Groß
Tiny phone, tiny mail

**Comment by pkrakowiak** [comment]
Yes, it does. But unit tests are not recognized (they worked in the same project when I previously used MSpec runner installed from batch files on my old computer).

![zrzut ekranu 188](https://cloud.githubusercontent.com/assets/736489/5833520/7063c094-a154-11e4-9e86-19a4523ebcec.png)

![zrzut ekranu 189](https://cloud.githubusercontent.com/assets/736489/5833522/7460b0d0-a154-11e4-9790-a6a02eab38e3.png)

**Comment by danielmarbach** [comment]
The important thing is: are the specs detected or not?

**Comment by danielmarbach** [comment]
What is your timezone? Might be able to do a remote session during lunch

**Comment by pkrakowiak** [comment]
They are not detected by the R# Test Runner, but they are detected and ran with the command line MSpec tool. My timezone is CEST, our local time is the same.

**Comment by neoeinstein** [comment]
Did you attempt restarting the Visual Studio process? When I installed the R# plugin for the first time a couple days ago myself, R# didn't recognize the tests either until I quit out and restarted VS. Once that happened, R# began detecting and annotating the specs.

**Comment by pkrakowiak** [comment]
Yes, I did. It's started and closed every day, sometimes multiple times.

**Comment by pkrakowiak** [comment]
The only other thing I can think of is having a non-Latin character in my path. But I think VS itself doesn't mind. Here's additional information on how my R# plugins are loaded:

Information about extension Machine.Specifications.Runner.Resharper

Version: 1.0.0
Description: Machine.Specifications.Runner.Resharper provides a Resharper runner for the Context/Specification framework Machine.Specifications
Authors: Aaron Jensen,  Alexander Groß,  Daniel Marbach,  et al.
Tags: test, unit, testing, context, specification, bdd, tdd, mspec, runner, resharper
Dependencies: ReSharper (? 8.2 && < 8.3)
License: http://github.com/machine/machine.specifications.runner.resharper/blob/master/License.txt
Project: http://github.com/machine/machine.specifications.runner.resharper

This extension contains: a Plugin, Settings

ExtensionManager (Info): Adding extension 'Machine.Specifications.Runner.Resharper' 1.0.0 from 'Default' source
ExtensionManager (Info): Enabling extension 'Machine.Specifications.Runner.Resharper'
ExtensionPluginSource (Info): Discovering plugins from extension 'Machine.Specifications.Runner.Resharper'
NuGetExtension (Info): Looking for 'plugins' files in the Machine.Specifications.Runner.Resharper package folder at C:\Users\Paweł\AppData\Local\JetBrains\ReSharper\vAny\packages\Machine.Specifications.Runner.Resharper.1.0.0
NuGetExtension (Info): The package contains no files in ReSharper\v8.2\vs12.0\plugins
NuGetExtension (Info): The package contains no files in VisualStudio\v12.0\vs12.0\plugins
NuGetExtension (Info): Found 3 files under ReSharper\v8.2\plugins
NuGetExtension (Info): The package contains no files in VisualStudio\v12.0\plugins
NuGetExtension (Info): The package contains no files in ReSharper\vAny\plugins
NuGetExtension (Info): The package contains no files in VisualStudio\vAny\plugins
NuGetExtension (Info): The package contains no files in DotNet\v1.0\plugins
NuGetExtension (Info): The package contains no files in DotNet\vAny\plugins
ExtensionPluginSource (Info): Discovered plugins 'Machine.Specifications Runner for ReSharper 8.2' from extension 'Machine.Specifications.Runner.Resharper'
ExtensionPluginSource (Info): Enabling plugin 'Machine.Specifications Runner for ReSharper 8.2' from extension 'Machine.Specifications.Runner.Resharper'
ExtensionPluginSource (Info): Adding 1 plugin(s) from extension 'Machine.Specifications.Runner.Resharper'
PluginLoader (Info): Plugin has 3 files under the C:\Users\Paweł\AppData\Local\JetBrains\ReSharper\vAny\packages\Machine.Specifications.Runner.Resharper.1.0.0\ReSharper\v8.2\plugins folder: Machine.Specifications.ReSharper.Provider.8.2.dll, Machine.Specifications.ReSharper.Runner.8.2.dll, Machine.Specifications.Runner.Utility.dll.
ExtensionsExternalAnnotationsFileProvider (Info): Discovering external annotations files for extension 'Machine.Specifications.Runner.Resharper'
NuGetExtension (Info): Looking for 'annotations' files in the Machine.Specifications.Runner.Resharper package folder at C:\Users\Paweł\AppData\Local\JetBrains\ReSharper\vAny\packages\Machine.Specifications.Runner.Resharper.1.0.0
NuGetExtension (Info): The package contains no files in ReSharper\v8.2\vs12.0\annotations
NuGetExtension (Info): The package contains no files in VisualStudio\v12.0\vs12.0\annotations
NuGetExtension (Info): The package contains no files in ReSharper\v8.2\annotations
NuGetExtension (Info): The package contains no files in VisualStudio\v12.0\annotations
NuGetExtension (Info): The package contains no files in ReSharper\vAny\annotations
NuGetExtension (Info): The package contains no files in VisualStudio\vAny\annotations
NuGetExtension (Info): The package contains no files in DotNet\v1.0\annotations
NuGetExtension (Info): The package contains no files in DotNet\vAny\annotations
ExtensionsExternalAnnotationsFileProvider (Info): No external annotations files found for extension 'Machine.Specifications.Runner.Resharper'
ExtensionSettingsLoader (Info): Discovering settings files for extension 'Machine.Specifications.Runner.Resharper'
NuGetExtension (Info): Looking for 'settings' files in the Machine.Specifications.Runner.Resharper package folder at C:\Users\Paweł\AppData\Local\JetBrains\ReSharper\vAny\packages\Machine.Specifications.Runner.Resharper.1.0.0
NuGetExtension (Info): The package contains no files in ReSharper\v8.2\vs12.0\settings
NuGetExtension (Info): The package contains no files in VisualStudio\v12.0\vs12.0\settings
NuGetExtension (Info): The package contains no files in ReSharper\v8.2\settings
NuGetExtension (Info): The package contains no files in VisualStudio\v12.0\settings
NuGetExtension (Info): Found 3 files under ReSharper\vAny\settings
NuGetExtension (Info): The package contains no files in VisualStudio\vAny\settings
NuGetExtension (Info): The package contains no files in DotNet\v1.0\settings
NuGetExtension (Info): The package contains no files in DotNet\vAny\settings
ExtensionSettingsLoader (Info): Discovered 3 settings files files under folder C:\Users\Paweł\AppData\Local\JetBrains\ReSharper\vAny\packages\Machine.Specifications.Runner.Resharper.1.0.0\ReSharper\vAny\settings from extension 'Machine.Specifications.Runner.Resharper': ReSharper.FileTemplates.DotSettings, ReSharper.LiveTemplates.DotSettings, ReSharper.SurroundTemplates.DotSettings
ExtensionSettingsLoader (Info): Adding 3 settings file(s) from extension 'Machine.Specifications.Runner.Resharper'

**Comment by mooondogg** [comment]
Has this issue been solved? I have the exact same problem. I cant get MSpec Runner to  work with Resharper 8.2 in VS 2013 and also not in VS2012. I am using version 1.0.0 of Machine.Specification.Runner.Resharper.

**Comment by danielmarbach** [comment]
Yes it is solved. Did you install over gallery?

**Comment by pkrakowiak** [comment]
When was it solved? I checked for updates a couple days ago but there were none.

**Comment by danielmarbach** [comment]
@pkrakowiak Add me in skype, I'll have a look

**Comment by mooondogg** [comment]
I did install it from the gallery. I also installed in on another computer, but it didn't work there either.

**Comment by pkrakowiak** [comment]
@danielmarbach Last published version in the R# gallery is from 2014-12-29.

**Comment by mooondogg** [comment]
It's the version published 2014-12-29  I have installed which I cannot get to work. I get "No tests found in project"

**Comment by mooondogg** [comment]
I finally found a solution for my problem. I used the latest Mspec runner for resharper, but my test project referenced an older version of mspec. When I referenced a newer one, everything worked as it should.

**Comment by danielmarbach** [comment]
Yes. The new runner is only compatible with 0.9.0 and higher

**Comment by pkrakowiak** [comment]
Ouch! Then it's no surprise it didn't work for me - we reference a really old MSpec version in that project (I tried to update it yesterday with NuGet packages to no avail, but that's another story). I upgraded ReSharper to version 9 this week and installed the MSpec Test Runner using JetBrains' new plugin installer. It works fine (except in this project). I think we can close this report.
