### ISSUE TITLE
Resharper 9 File Layout

### ISSUE THREAD

**Issue by tthibodeau** [machine/machine.specifications#270]
I've been trying to get the [MSpec file layout](http://therightstuff.de/2008/09/16/ReSharper-Type-Members-Layout-For-MSpec-02.aspx) working with Resharper 9 but it just doesn't reorder the delegates.

Can we add a working Resharper file layout.xml file to the repository?

Thank you

**Comment by agross** [comment]
This a bug in ReSharper that is unfixed but reported to JetBrains. I don't have the link handy because I'm not in front of a computer right now. 




Alex
-- 
Alexander Groß
Tiny phone, tiny mail

**Comment by tthibodeau** [comment]
Thank you!

https://youtrack.jetbrains.com/issue/RSRP-432483

**Comment by NameOfTheDragon** [comment]
FYI, code re-ordering is working for me in R# 9. I did have a hiccup with it and I seem to remember I had to be careful which ‘layer’ I put the rules into. A bit later I will try your specific test case and let you know what happens and try to work out what I’ve done differently.

Regards,
Tim Long

**Comment by tthibodeau** [comment]
Can you post your type layout xml for MSpec so I can try it out?

Thanks.

**Comment by agross** [comment]
These are my MSpec-specific ReSharper settings: https://www.dropbox.com/s/p5h9tfkq7kwcrn3/MSpec.DotSettings?dl=0

**Comment by tthibodeau** [comment]
Thank you, @agross. I should have been more specific. I am interested in seeing the working type layout xml that @NameOfTheDragon mentioned in his post. :)
