### ISSUE TITLE
System.InvalidCastException - [A] cannot be cast to [B]

### ISSUE THREAD

**Issue by edmolko** [machine/machine.specifications#272]
Hello,

I'm running into a situation where I'm getting an InvalidCastException:

Imagine I have a class named MyClass in my TestProject:

public class MyClass : IClass
{
...
}

and a Factory:

public class Factory : IFactory
{
	public IClass CreateClass()
	{
	...
	}
}

I have a scenario like this:

[Subject(typeof(Factory))]
public class When_something
{
	static IFactory _subject;
	.
	.
	.
	
	It should_work = () =>
	{
		var myClassInstance = (MyClass)_subject.CreateClass();
	}
}

I'm getting the following exception:

An exception of type 'System.InvalidCastException' occurred in TestProject.dll but was not handled in user code

Additional information: [A]TestProject.MyClass cannot be cast to [B]TestProject.MyClass. Type A originates from 'TestProject, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' in the context 'Default' at location 'C:\Users\[myuser]\AppData\Local\Temp\vhifxdi2.f5w\Machine Specifications Runner\assembly\dl3\e7391b89\69fa534a_877bd001\TestProject.dll'. Type B originates from 'TestProject, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' in the context 'LoadNeither' at location 'C:\Projects\TestProject\src\tests\TestProject\bin\Debug\TestProject.dll'.

**Comment by danielmarbach** [comment]
Have you tried disable shadow copying in the resharper settings?

**Comment by edmolko** [comment]
That was it! Thanks
