### ISSUE TITLE
ReSharper 9.1 Support

### ISSUE THREAD

**Issue by matkoch** [machine/machine.specifications#273]
As titled. Any plans?

**Comment by danielmarbach** [comment]
https://resharper-plugins.jetbrains.com/packages/Machine.Specifications.Runner.Resharper9/1.1.0-Beta0000

**Comment by matkoch** [comment]
Sorry :) Didn't notice because it's a pre-release extension.

**Comment by matkoch** [comment]
Where is the actual source for that? https://github.com/machine/machine.specifications.runner.resharper is out of date.

**Comment by matkoch** [comment]
I can also add, that the runner doesn't run any tests. Neither with nuget package 8.2, nor 9.1, nor pre-release 10.

**Comment by danielmarbach** [comment]
No it's not. See branches

**Comment by danielmarbach** [comment]
You have to install it via the extension gallery. Not use the nuget

**Comment by matkoch** [comment]
I'm not talking about NuGet here. If you look at the extension gallery, only the Unstable0006 version is selectable. I think the package naming went wrong. The pre-release text is sorted alphanumerically. Therefore "Unstable" is a higher version than "Beta"... I think you should stick to either one of them. Everything with pre-release is *unstable* per definition. So better use *alpha*, *beta*, etc...

You can also see this at https://resharper-plugins.jetbrains.com/packages/Machine.Specifications.Runner.Resharper9/1.1.0-Beta0000

Version	Downloads	Last updated
Machine.Specifications.Runner.Resharper 1.1.0-Unstable0006	98	**Sunday, April 12 2015**
Machine.Specifications.Runner.Resharper 1.1.0-Beta0000-0001	1	**Saturday, April 18 2015**
Machine.Specifications.Runner.Resharper 1.1.0-Beta0000 (this version)	1	**Sunday, April 12 2015**

**Comment by danielmarbach** [comment]
Seems to be a bug in the gallery. It doesn't respect semver. I'll release soon anyway. Other users reported it works

**Comment by matkoch** [comment]
Taken from http://semver.org/ number 11:

> Precedence for two pre-release versions with the same major, minor, and patch version MUST be determined by comparing each dot separated identifier from left to right until a difference is found as follows: identifiers consisting of only digits are compared numerically and identifiers with letters or hyphens are compared lexically in ASCII sort order. Numeric identifiers always have lower precedence than non-numeric identifiers. A larger set of pre-release fields has a higher precedence than a smaller set, if all of the preceding identifiers are equal. Example: 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0

**Comment by danielmarbach** [comment]
Doesn't that mean beta is higher than unstable?

**Comment by matkoch** [comment]
Nope. If 1.0.0-alpha < 1.0.0-beta, then also 1.0.0-beta < 1.0.0-unstable :grin:
