### ISSUE TITLE
NuGet gallery is getting very polluted

### ISSUE THREAD

**Issue by NameOfTheDragon** [machine/machine.specifications#276]
The NuGet gallery is becoming very 'polluted' with all the development components and now, there are some packages appearing from someone called 'signedpackages' that ReSharper is picking up in preference to the 'real' packages.

It is becoming quite confusing and difficult to get the right packages.

Do all the 'development' packages really have to be pushed to the public NuGet feed? If you have a TeamCity server, which I think you do, would it not be better to keep those on a separate feed?

**Comment by danielmarbach** [comment]
That was a one of my Not so good decisions. It would be better to push unstable packages to myget.

**Comment by NameOfTheDragon** [comment]
It's not the unstable packages that are the problem, those are fine since NuGet doesn't display them by default... it's all the development dependencies. The problem is they are there now and there's no easy way to delete them.



--Tim



________________________________

**Comment by danielmarbach** [comment]
I could try to get rid of them

**Comment by robertcoltheart** [comment]
Mostly cleaned up now, closing this
