### ISSUE TITLE
VS Test Adapater - Fatal error while executing test when using Behaviors

### ISSUE THREAD

**Issue by JarrodJ83** [machine/machine.specifications#277]
I tried to start using behaviors in my specs and as soon as I did I started getting this exception when I try to run or debug my tests via the VS Test Adapter. If I comment out the Behaves_Like and put the assertion directly in my spec things work fine. 

So, this works fine:

```c#
public class Event_Spec
{
     protected static MemoryCallSvc CallSvc;
     // omitted out code for brevity

     It sends_an_event = () => CallSvc.Calls.Any();
     //Behaves_like<An_Event_Was_Raised> an_event_has_been_sent;
}
```

but this causes the exception:

```c#
public class Event_Spec
{
     protected static MemoryCallSvc CallSvc;
     // omitted out code for brevity

     //It sends_an_event = () => CallSvc.Calls.Any();
     Behaves_like<An_Event_Was_Raised> an_event_has_been_sent;
}
```

here is my behavior:

```c#
[Behaviors]
public class An_Event_Was_Raised
{
     protected static MemoryCallSvc CallSvc;

     It sends_an_event = () => CallSvc.Calls.Any();
}
```

Here is my visual studio info:
Microsoft Visual Studio Ultimate 2013
Version 12.0.31101.00 Update 4
Microsoft .NET Framework
Version 4.5.51650

I'm using MSpec v0.7.0

**Comment by JarrodJ83** [comment]
Also I forgot to mention that the tests run fine even with the behaviors if i run using mspec.exe via the command line so it seems isolated to the VS Test Adapter.

**Comment by JarrodJ83** [comment]
Just realized there was a separate repo for the test adapater. Will move my post there. Sorry!

**Comment by cjjohansen** [comment]
Did you maange to find a solution for this?
