### ISSUE TITLE
Support for .NET Core CLR and DNX

### ISSUE THREAD

**Issue by kawazoe** [machine/machine.specifications#280]
I would love to be able to use MSpec in an ASP.NET vNext application. I think now would be a good time to start thinking about what is needed to support dnxcore50 and getting the tests to run in xproj-based projects.

I know that xUnit is already supporting those (including their Resharper integration) so this is definitely something feasible.

**Comment by drauch** [comment]
Let's wait for the second part of http://blog.marcgravell.com/2015/11/the-road-to-dnx-part-1.html ;)

**Comment by ivanz** [comment]
I have just done my first "dotnet test" on .Net Core with mspec using:

https://github.com/ivanz/dotnet-test-mspec
https://einari/machine.specifications.core

**Comment by ivanz** [comment]
Heads up that the progress of this will be tracked in #296

**Comment by ivanz** [comment]
Closing this, because the support for .Net Core has just landed in master. If you want to keep track of the progress I suggest subscribing #296 or if you want to know when it's released: #308  (note that the release will include a bunch of things - not just mspec.dll itself)
