### ISSUE TITLE
Default namespace for JetBrains annotation attributes

### ISSUE THREAD

**Issue by ulrichb** [machine/machine.specifications#282]
Using the method by internalizing all annotation types (as described in [this blog post](https://blog.jetbrains.com/dotnet/2015/08/12/how-to-use-jetbrains-annotations-to-improve-resharper-inspections/)) we could use the default namespace for the JetBrains annotation attributes (instead of `Machine.Specifications.Annotations`). 

This way, users don't have to configure the custom namespace in the ReSharper settings, and the `[MeansImplicitUse]` annotations of `[Subject]` and `[Behaviors]` work out of the box.

**Comment by drauch** [comment]
:+1: If you can provide a suitable pull request, I am willing to merge it :-)
