### ISSUE TITLE
It delegates from base classes ignored

### ISSUE THREAD

**Issue by ajj3085** [machine/machine.specifications#284]
There are sometimes where I am testing an action, but slight variations change the outcome of the same exact call.  Its fairly common to have some assertions that should be true regardless of variation, and then some specific to each variation.  Consider the follow code:

	[Subject(typeof(string))]
	internal abstract class InheritiedAssertsionsIgnored {
		Establish sharedContext = () => Console.WriteLine("Shared context");
	}

	internal abstract class ScenarioA : InheritiedAssertsionsIgnored {
		Establish scenarioAContext = () => Console.WriteLine("ScenarioA context");

		Because sharedAction = () => Console.WriteLine("Shared action");

		It assertTrueInAllVariations = () => Console.WriteLine("Shared assertion");
	}

	internal class ScenarioAVariation1 : ScenarioA {
		Establish variation1Context = () => Console.WriteLine("Variation 1 context");

		It it1 = () => Console.WriteLine("ScenarioAVariation1 It1");

		It it2 = () => Console.WriteLine("ScenarioAVariation1 It2");
	}

	internal class ScenarioAVariation2 : ScenarioA {
		Establish variation2Context = () => Console.WriteLine("Variation 2 context");

		It it1 = () => Console.WriteLine("ScenarioAVariation2 It1");

		It it2 = () => Console.WriteLine("ScenarioAVariation2 It2");
	}

When Run, I would expect to see assertTrueInAllVariations to show under the tests run for both ScenarionAVariation1 and ScenarioAVariation2.  It seems counter intiutive that Establishes from base classes are executed, as well as the Because (assuming there's only one in the chain), but It delegates are not.

**Comment by drauch** [comment]
This seems to be per-design. I don't know the exact reason behind it, however, you should use Behaviors to overcome your problem.

**Comment by agross** [comment]
Yes, this is per design.

**Comment by ajj3085** [comment]
It seems a rather peculiar design choice; why force the use of something non-intuitive over something OO developers are always well familiar with and, if you search around, intuitively attempt and then wonder why it doesn't work.  **Especially** when `Because` and `Establish` delegates **are** inherited.

I like Mspec because one of its stated goals is to reduce the amount of noise / code needed to write tests.  Behaviors goes completely against that principle.

**Comment by agross** [comment]
@ajj3085 It's a design choice that is also enforced by e.g. rspec that MSpec pulled a lot from. With rspec you don't have inheritance (but nesting) and rspec's `before` blocks (~ `Establish`) are executed top-down, but not rspec's `it`s.

**Comment by ajj3085** [comment]
I understand its a design choice, but it's one I feel should be reconsidered.  I also understand that MSpec was inspired by RSpec, but I don't necessarily think that it should keep feature parity.  MSpec in this case should work as .Net developers expect it to, and I know there have been others which have expressed similar opinions about behaviors.  I'm not really interested in what RSpec does as that's not the framework I'm using (and if I were, I'd be really annoying about not utilizing inheritance).

Again, it makes little sense given that MSpec is supposed to get out of the way, but behaviors don't do that.  Its also surprising when Because and Establish CAN be inherited.

**Comment by agross** [comment]
That design decision has been made years ago and I feel we won't break things. Especially now that the project is not actively maintained.
