### ISSUE TITLE
FYI: Machine.Specifications.Runner.VisualStudio 2.0.0-rc1 is out (IDE, TFS, VSO, Visual Studio Team Services support)

### ISSUE THREAD

**Issue by ivanz** [machine/machine.specifications#289]
Hi all,

Just wanted to let you know that there has been a bunch of work happening in the Visual Studio (vstest) adapter for MSpec lately (by me) and the first RC for the 2.0.0 release is out with some substantial improvements.

This adapter comes in either as a Visual Studio extension and as of recently - as a NuGet package, which provides out of the box MSpec support for Visual Studio Online (now Visual Studio Team Services), TFS, etc.

Get it: https://github.com/machine-visualstudio/machine.vstestadapter/releases/tag/v2.0.0-rc1

### What's new and improved

This is a significant update to the Test Adapter:

* New test discovery engine built directly on top of MSpec replaces old Mono.Cecil based one:

 * Full support for `[Behavior]` and `Behaves_like<>` and everything MSpec
 * Full support for assembly binding (`.config`) during test discovery (and execution)

* Greatly improved support for Visual Studio Team Services, TFS,etc (works out of the box with the NuGet package)

 * Major performance improvements when running whole test assemblies
 * Much clearer test result output
 * Fully compatible with VS parallel assembly execution (enabled through  MaxCpuCount  set to 0 in  *.runsettings )

* Inner exceptions are now displayed in failed test results

* Tests in Visual Studio IDE are now displayed as English text

![image](https://cloud.githubusercontent.com/assets/79742/13713366/88985202-e7c0-11e5-9019-5295190ba649.png)

![image](https://cloud.githubusercontent.com/assets/79742/13713375/923e9f32-e7c0-11e5-8689-045ca9949486.png)

![image](https://cloud.githubusercontent.com/assets/79742/13714426/5b1428be-e7c6-11e5-9afd-60486c5c3482.png)

**Comment by drauch** [comment]
Is it planned to support R# as well?

**Comment by ivanz** [comment]
@drauch  in what sense?

**Comment by drauch** [comment]
Sorry, should have given my post more time: you have created a new test discovery engine. Is it reusable for the MSpec R# test runner project?

**Comment by ivanz** [comment]
@drauch  I am afraid I don't know anything about mspec and R# specifically, but as far as this test runner is concerned - it operates on binary level (*.dll) and uses mspec to discover and run tests. So if you are able to run your tests with the mspec command line tool then this adaptor should work.
