### ISSUE TITLE
Inheriting from external nested class fails

### ISSUE THREAD

**Issue by WaffleSouffle** [machine/machine.specifications#292]
Inheriting from external class works.
Inheriting from external nested class fails.
See attached file for example (it's a .cs file renamed for upload functionality to work).

[MSpec_inheritance_issue.txt](https://github.com/machine/machine.specifications/files/217211/MSpec_inheritance_issue.txt)

NuGet packages:
Machine.Specifications 0.9.3.0
Machine.Specifications.Clr4 0.9.3.0
Machine.Specifications.Should 0.8.0.0

**Comment by WaffleSouffle** [comment]
Further investigation indicates it's a problem with abstract. If Given_outer is not abstract in the attached examples, then the test passes.

**Comment by WaffleSouffle** [comment]
Sorry forgot to post link to pull-request fix...
https://github.com/machine/machine.specifications/pull/291

**Comment by robertcoltheart** [comment]
No longer seeing this issue in the latest version.
