### ISSUE TITLE
Async support

### ISSUE THREAD

**Issue by SlyNet** [machine/machine.specifications#293]
Establish, Because and It should support async

**Comment by NameOfTheDragon** [comment]
@SlyNet I would find it helpful if you could give an example of how you would envisage this working and perhaps say something about why it would be useful. From your description, it isn't self-evident to me what you are actually requesting.

**Comment by alistair** [comment]
```
Because i_want_to_handle_async = async () => {
   Result = await httpClient.GetAsync(....)
}

It should_have_the_result_available = () => {
   Result.ShouldNotBeNull();
}

static string Result;
```

**Comment by mikeblakeuk** [comment]
Any news on this feature?

**Comment by robertcoltheart** [comment]
We've successfully used the above pattern in our code and it _works_, although it probably shouldn't be relied on. This is slated for 2.0, and for now the usable workaround is just to call `Wait()` or `Result` on your calls.

**Comment by mikeblakeuk** [comment]
Is there a 2.0.0 preview we can try?

**Comment by mikeblakeuk** [comment]
We really would love async in our machine spec tests.
Is there a preview branch we can try? Thanks

**Comment by robertcoltheart** [comment]
I was hoping to bundle this with `2.0` but the refactor is taking more time than I'd like. I'll back-port this feature into `1.0` for now. See PR for implementation.
