### ISSUE TITLE
CI Build on Linux build agent

### ISSUE THREAD

**Issue by einari** [machine/machine.specifications#295]
Suggest to maintain a second environment for building to make sure to keep the .NET Core version compatible cross platform. 

If possible and if it makes sense; use TeamCity and the CodeBetter CI. 

Alternatively, Travis could be used:
http://andrewlock.net/adding-travis-ci-to-a-net-core-app/

**Comment by NameOfTheDragon** [comment]
TeamCity is is already cross-platform – it just needs an appropriate build agent. I don’t know what the arrangements are at CodeBetter but I expect it could be arranged without involving a whole new build system.
--Tim Long

**Comment by einari** [comment]
Good point.  I'm on it - will try to get in touch with them.
