### ISSUE TITLE
Strongly signed version of Machine.Specifications

### ISSUE THREAD

**Issue by ivanz** [machine/machine.specifications#298]
There used to be a strongly signed version on Nuget and still is, but the current build pipeline doesn't create nor publish a "-Signed" package.

Download numbers of the Signed packages are quite low.

**Comment by lwuckel** [comment]
Where can I find the "-Signed" package v0.11 ?
Or how can I build it for myself?

Regards, Lars

**Comment by JohannesHoppe** [comment]
Support for strong-name signing was dropped, back then in early 2014.
see https://github.com/machine/machine.specifications/issues/190

**Comment by BrunoJuchli** [comment]
@JohannesHoppe  actually according to #190 that's not the Case.
In short:

Daniel Marbach asked whether there was a reason not to drop it - a reason why there should be a signed version, and it has been found:

> It's true when you have a signed assembly with an InternalsVisibleTo attribute to a specification assembly the specification assembly needs to be strong named too. I'm closing this issue. 

NameOfTheDragon later found a specific workaround for his use-case - not signing non-release builds and hence testing non-release builds.

However, Daniel never said that signed-builds will be removed.
