### ISSUE TITLE
Support for IDE integrations (Design-Time test protocol)

### ISSUE THREAD

**Issue by ivanz** [machine/machine.specifications#303]
Basically implement this protocol: https://docs.microsoft.com/en-us/dotnet/articles/core/tools/test-protocol

Xunit and nunit have implemented it, so can be used as reference

**Comment by ryudice** [comment]
Are there still plans to work on this? I can work on this.

**Comment by ivanz** [comment]
There is too much instability at this point in the .NET tooling land - especially with the currently in progress switch back to MSBuild (from project.json). Once we have a stable protocol - we can look at it. 

Related: https://github.com/machine/machine.specifications.runner.resharper/issues/46

**Comment by ivanz** [comment]
dotnet-test-mspec is no longer relevant in the new "csproj" world, so closing this issue. The new world is VsTest adapter (we have one - machine.vstestadpater) and we already have design-time support there.
