### ISSUE TITLE
Would you mind if I add the ability to include a failure message in all assertions?

### ISSUE THREAD

**Issue by penderi** [machine/machine.specifications#314]
I find it helps those supporting code after me (or after I've left code behind for 6m+) if I have a failure message for the assertion fail.

I realies some BDD fanboys may hate this, this my question. 

If there's no opposition I can post a PR in no time... just canvassing opinion...

**Comment by agross** [comment]
Can you give an example of what you mean? I don't know what you mean, because assertions usually have a message.

**Comment by penderi** [comment]
Hi @agross "!!
Yes I can. I'm trying to say I would like to use the following:

testId.ShouldEqual(userId, "Did not request userId");

.... and seeing the custom message in the test output...

**Comment by agross** [comment]
OK, I get it now. You should submit your PR here:
https://github.com/machine/machine.specifications.should

**Comment by penderi** [comment]
OH WOW. Awesome. I certainly will!
