### ISSUE TITLE
Support for CI reports (Bamboo etc)

### ISSUE THREAD

**Issue by ryudice** [machine/machine.specifications#317]
Is there a way currently to generate test reports in NUnit format? There doesnt seem to be an easy way to integrate Mspec tests into Bamboo, this would be an easy workaround.

**Comment by ivanz** [comment]
There is no NUnit format output out of the box, but there is already some other outputs and an XML one here: https://github.com/machine/machine.specifications.reporting/tree/master/Machine.Specifications.Reporting/Generation/Xml

The console runner (but not the .net core one yet) uses this lib for outputs.
