### ISSUE TITLE
Support running .NET Core tests in .csproj projects

### ISSUE THREAD

**Issue by danielgerlag** [machine/machine.specifications#322]
My project was using the project.json format, but then I migrated to VS 2017 and it converted everything to .csproj files, but the "testRunner" option didn't seem to make it.  How to I use the cli test runner on the .csproj format?

**Comment by ivanz** [comment]
I will start looking into this shortly now that I have a copy of VS2017. I think dotnet-test-mspec will be no more without project.json and likely the solution is an update to the the machine.visual studio test adapter to support multi-targeting.

**Comment by JohannesHoppe** [comment]
I stumbled across the same issue.
Has anybody a workaround to run the mspec tests after migration to `.csproj`?

**Comment by danielgerlag** [comment]
Thank you, it's working inside Visual Studio - awesome. 👍 :)
How do I get the "dotnet test" command to discover the tests?

**Comment by ivanz** [comment]
It *should* work - I've just raised an issue with the vstest team: https://github.com/Microsoft/vstest/issues/606

**Comment by ivanz** [comment]
A temporary workaround which works for .Net Core tests (but breaks running .NET Framework ones): 

dotnet test -a "%USERPROFILE%\.nuget\packages\machine.specifications.runner.visualstudio\2.2.1" 

(-a is telling dotnet test where to look for test adapters)

**Comment by ivanz** [comment]
This is all now fixed in version 2.2.2 - no need for any workarounds 🎉 🎉 🎉 I've updated the wiki to provide info on how to migrate from project.json to csproj: https://github.com/machine/machine.specifications/wiki/.NET-Core-(.NET-CLI)
