### ISSUE TITLE
Performance: Establish/Cleanup are being called for every "It" (in Visual Studio IDE)

### ISSUE THREAD

**Issue by ivanz** [machine/machine.specifications#325]
**Migrated from vstest adapter repo**

IDEs and e.g. VS adapter allow to run a single test ("It"), but since MSpec core doesn't support that currently adapters are running the whole spec (class).

Note: need to watch out when implementing this so that Behavior's It are supported properly.

**Comment by einari** [comment]
The core supports running specific members - for the old ´dotnet test´runner - I implemented its usage [here](https://github.com/machine/dotnet-test-mspec/blob/master/src/dotnet-test-mspec/Execution/SpecificSpecificationRunner.cs)

**Comment by ivanz** [comment]
Good point. I was mechanically copy pasting/moving issues from the machine vstest adapter repo to here to centralize issue management.

**Comment by eskitek** [comment]
@einari , since the mspec core now supports running specific members as you mentioned, does that mean that this issue is fixed? Or does additional work still need to be done to make machine.vstestadapter run Establish/Cleanup once per spec instead of once per "It"?

**Comment by robertcoltheart** [comment]
This should be fixed with https://github.com/machine/machine.vstestadapter/pull/87
