### ISSUE TITLE
TestCaseFilter support

### ISSUE THREAD

**Issue by ivanz** [machine/machine.specifications#327]
**Migrated from vstest adapter repo**

 it is whatever vstest supports, so test category, class name etc.

/TestCaseFilter:"TestCategory=Nightly|FullyQualifiedName=Namespace.ClassName.MethodName"

**Comment by einari** [comment]
We should also get a pull request in for the documentation for [VSTest](https://github.com/Microsoft/vstest-docs/blob/master/docs/filter.md).

I would be happy to jump in on this particular feature - as I really need it now for VSCode :) 

One type of filter I want to add would be to support having a file and a line number passed in. That way I can get VSCode information directly sent in as filter ([variables in VSCode](https://code.visualstudio.com/Docs/editor/tasks#_variable-substitution))

**Comment by ivanz** [comment]
I am wondering if we can "upgrade" the existing [RunOptions](https://github.com/machine/machine.specifications/blob/master/Source/Machine.Specifications/Runner/RunOptions.cs) in MSpec to support those extra scenarios in a backwards compatible way such that if an older Machine.Specification version is used - it still works, but the filters are not applied. 

The main reason I added the TestController in MSpec was to be able to use simple reflection for running tests and I didn't actually intend it to be a filtering mechanism itself, but as it happened at the time it was a convenient way to use it for that. and it already takes in a string xml of runOptions in one of its constructors: https://github.com/machine/machine.specifications/blob/master/Source/Machine.Specifications/Controller/Controller.cs#L27

end of brain dump :)

**Comment by MattRyan** [comment]
I have created pull request #352 to expand RunOptions to include a context and specification filters. #

**Comment by mikeblakeuk** [comment]
@einari / @MattRyan Can you try the latest version (beta) of the adapter please. thanks

**Comment by robertcoltheart** [comment]
Please let me know once you're happy and I can close this issue.

**Comment by mikeblakeuk** [comment]
https://github.com/microsoft/vstest-docs/pull/230/files
