### ISSUE TITLE
Cannot see MSpec unit tests in ReSharper UnitTest Session

### ISSUE THREAD

**Issue by JayeshThamke** [machine/machine.specifications#332]
I have ReSharper installed (2017.1.3) in VS2017 and Machine Specifications latest packages from NuGet pm. In .NET Core  Library Project, I have created few unit tests. However, I cannot see them in ReSharper -> UnitTest and creating any unit test session. Test running from .NET CLI with dotnet test command returns the test result. I want to see in case of test failure which test has failed in ReSharper session explorer. How can I get such results? I am not sure if this is a limitation from ReSharper side.
Thanks,
Jay

![mspec_resharper_dotnetcore](https://user-images.githubusercontent.com/28365503/27157537-56556142-5162-11e7-9fc1-4ab3107edb0f.png)

**Comment by ivanz** [comment]
Thanks for the report. As per https://github.com/machine/machine.specifications.runner.resharper/issues/46 - as of this moment the ReSharper mspec extension doesn't support running .NET Core . The ticket mentions what needs to be implemented if you decide to give it a go :)
