### ISSUE TITLE
Does machine specification support re-run?

### ISSUE THREAD

**Issue by sophie2805** [machine/machine.specifications#336]
hi there,
Our UI automation tests are using machine specification framework, run in team city. Now, I want to re-run the failed tests automatically. Team city does not support to re-run the specific failed tests, it re-run the whole suite (a test fail, is considered whole suite fail). I looked around, I found MSBuild Runner support re-run. So I am thinking that, if MSpec framework and mspec-x86-clr4.exe support re-run, my problem would be solved perfectly.

**Comment by ivanz** [comment]
There is no "re-run" functionality out of the box. Can you point me to how that is achieved for msbuild? 

In general I imagine that the process will involve storing the output of the test run, parsing it to pick up only the fail tests and passing that into the test filter for the re-run.

**Comment by NameOfTheDragon** [comment]
"Re-run" failed tests would be a test runner feature, not something that is inherent to the test framework itself. Normally on a build server you want to run the entire test suite, so I don't expect a facility to run only previously failed tests to be offered in that scenario. To be honest, it would be an odd use of a build server. Is this by any chance an example of [The XY Problem](http://xyproblem.info/)?

**Comment by sophie2805** [comment]
Hi guys ,
NUnit framework has a [Retry(...)] attribute. It can rerun the failed test specific times. NUnit + MSBuild, they can re-run the failed tests.
Our Machine Specification + MSpec Runner seems not supporting re-run currently. But for UI automation regression (especially web UI automation, which is considered THE most fragile automation), re-run is a good feature to eliminate the false failures due to, like bad performance, internet delay, browser exception...
So, for now, I have to try to customize team city, pick out the failed tests from last run, let it re-run them. Like I said in the initial post, team city cannot do that for now. Thank you guys. Have a good day.

**Comment by BrunoJuchli** [comment]
@sophie2805 
how will you differentiate the reason for a sporadic failure? There are "positive" failures like concurrency issues. How will you make sure not to classify them as a "false failure"?

I'm asking because I'm wondering whether there is a way to automate the differentiation and whether this should be possible with the re-run feature.

**Comment by sophie2805** [comment]
@BrunoJuchli 
Hi, yes, you are right, it is very possible that failures are due to concurrency, re-run them separately they will pass, so issues are overlooked. But to be honest, it's hard to tell in UI automation regression, because there are many noises. I think for the concurrency issue, it's better to go with other type of automation, like load test, to identify.
