### ISSUE TITLE
netstandard 2.0 support for VS 15 tests

### ISSUE THREAD

**Issue by mynkow** [machine/machine.specifications#339]
I am looking the issues for the last 2-3 weeks but I still can't find help. Sorry if it is a duplicate

When I install **Machine.Specifications.Runner.VisualStudio** after build I get this  warning:
```
warning NU1701: Package 'Machine.Specifications.Runner.VisualStudio 2.2.3' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
```
and as you can guess there are no tests discovered.

Could you please help me to identify is it only me or it is a general issue?

**Comment by ivanz** [comment]
The runner works out of the box with anything that targets .NET Framework 4.6+ or/and .NET Core 1.1+ . I have just double-checked by creating a new .NET Core 2 Unit Test project, adding mspec and the runner nugets and it works fine.  Keep in mind that test projects in the .NET Core world have to be ".NET Core" type and not .NET Standard class libraries.

What project type are you installing the runner into and what are the target frameworks? Can you upload a repro somewhere?

**Comment by mynkow** [comment]
This is the code => https://github.com/Elders/Cronus.DomainModeling/tree/release-4.0.0/src

I get the warning from the first post when the project is netstandard 2.0

I also tried with .net core 2.0 but the test is still not discovered

**Comment by ivanz** [comment]
You are getting that nuget error, because you have a leftover `packages.config`  in the `Elders.Cornus.DomainModeling.Tests` project, which you need to delete and which is saying that the target framework for the MSpec packages should be net4.5 

Further note is that for `dotnet test` and Visual Studio built-in Test window stuff to work you need to add a reference to `Microsoft.NET.Test.Sdk` and the project has to target `netcoreapp1.1` or newer. The same requirements are applicable for mstest, nunit,etc. you can create a new test project in VS to see what that looks like for other test frameworks.

See the documentation here: https://github.com/machine/machine.specifications/wiki/.NET-Core-%28.NET-CLI%29

With the above changes everything works for me:

```
PS C:\code\mspec\Cronus.DomainModeling\src> dotnet test
Build started, please wait...
Build started, please wait...
Build started, please wait...
Build completed.

Test run for C:\code\mspec\Cronus.DomainModeling\src\Elders.Cronus.DomainModeling\bin\Debug\netstandard2.0\Elders.Cronus.DomainModeling.dll(.NETStandard,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
No test is available in C:\code\mspec\Cronus.DomainModeling\src\Elders.Cronus.DomainModeling\bin\Debug\netstandard2.0\Elders.Cronus.DomainModeling.dll. Make sure test project has a nu
get reference of package "Microsoft.NET.Test.Sdk" and framework version settings are appropriate and try again.

Build completed.

Test run for C:\code\mspec\Cronus.DomainModeling\src\Elders.Cronus.DomainModeling.Tests\bin\Debug\netcoreapp2.0\Elders.Cronus.DomainModeling.Tests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Build completed.

Test run for C:\code\mspec\Cronus.DomainModeling\src\UnitTestProject1\bin\Debug\netcoreapp2.0\UnitTestProject1.dll(.NETCoreApp,Version=v2.0)
Machine Specifications Visual Studio Test Adapter - Executing Specifications.
Machine Specifications Visual Studio Test Adapter - Executing tests in C:\code\mspec\Cronus.DomainModeling\src\Elders.Cronus.DomainModeling.Tests\bin\Debug\netcoreapp2.0\Elders.Cronus
.DomainModeling.Tests.dll
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Complete on 1 assemblies

Total tests: 20. Passed: 20. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 3.4712 Seconds
Machine Specifications Visual Studio Test Adapter - Executing Specifications.
Machine Specifications Visual Studio Test Adapter - Executing tests in C:\code\mspec\Cronus.DomainModeling\src\UnitTestProject1\bin\Debug\netcoreapp2.0\UnitTestProject1.dll
Complete on 1 assemblies

Total tests: 2. Passed: 2. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 2.9009 Seconds
```

**Comment by mynkow** [comment]
Thank you very much. Didn't know about the packages.config issue

**Comment by ivanz** [comment]
No worries. Yeah - packages should be managed only in the .csproj file now - I would have thought that `packages.config` will be ignored for "new style csproj", but doesn't seem to be the case (maybe oversight?)

**Comment by Y2zz** [comment]
dotnet core 2.0 not supported?

**Comment by Y2zz** [comment]
I am here to run resharper unit test in core 2.0 can not find the test method
