### ISSUE TITLE
Machine.Specifications.Runner.VisualStudio Doesn't Support dotnet --filter 

### ISSUE THREAD

**Issue by derekgreer** [machine/machine.specifications#342]
Machine.Specifications.Runner.VisualStudio v2.3.0 

The adaptor doesn't appear to respect anything passed to the dotnet.exe --filter parameter.

Are there any filters supported? 

Here's some examples one would expect to work:
dotnet --filer Tag!=integration
dotnet --filter Subject=component
dotnet -- filter ClassName~MySpecs

**Comment by robertcoltheart** [comment]
Duplicate of #327
