### ISSUE TITLE
Behaves_like when the [Behaviors] class is in an external assembly 

### ISSUE THREAD

**Issue by mynkow** [machine/machine.specifications#343]
`Behaves_like` is cool. I am trying to make it work when the `[Behaviors]` class is in an external assembly referenced by the assembly containing the specs. Is this possible with the current version?

https://github.com/machine/machine.specifications/wiki/Behaviors

**Comment by ivanz** [comment]
I don't see why it shouldn't work? Are you hitting a specific error/issue?

FYI you can have a look at some of the Behavior code here to get better understanding of what happens under the hood: https://github.com/machine/machine.specifications/blob/master/Source/Machine.Specifications/Factories/BehaviorFactory.cs#L21 - this is used in `ContextFactory`

**Comment by mynkow** [comment]
I will dive in. 

Basically when I use `[Behaviors]` class the tests are not discovered

**Comment by mynkow** [comment]
Sorry, the problem is me. The tests are sorted by project and when the `[Behaviors]` class in in another assembly the specs also are moved in the test explorer. I just didn't notice this.

Have a productive day. 10x
