### ISSUE TITLE
MSPEC Task for Cake

### ISSUE THREAD

**Issue by holytshirt** [machine/machine.specifications#346]
I've already done the work for this https://github.com/cake-build/cake/issues/74
I'm just raising this so people are aware.

Cake (C# Make) is a cross platform build automation system with a C# DSL to do things like compiling code, copy files/folders, running unit tests, compress files and build NuGet packages.

I've add to the Cake dsl to make it easy to run your mspec tests.
https://cakebuild.net/dsl/mspec/

An example looks like in the cake script
```
#tool "nuget:?package=Machine.Specifications.Runner.Console"

Task("Tests")
  .Does(() =>
        {
          MSpec("./bin/**/*.tests.dll", new MSpecSettings());
        });
```

**Comment by robertcoltheart** [comment]
Thanks!
