### ISSUE TITLE
Is not currently not supported core 2.0?

### ISSUE THREAD

**Issue by Y2zz** [machine/machine.specifications#347]
**Core 2.0 project**, I have installed

Machine.Specifications 0.12.0
Machine.Specifications.Runner.VisualStudio 2.6.1
ReSharper Plugin 2.1.1

**Test methods can not be displayed in the test session**

**Comment by alain27espina** [comment]
Have you tried referencing **Microsoft.NET.Test.sdk**? It will at least show up in Test Explorer. I'm not sure about ReSharper. Worth a try.

**Comment by Y2zz** [comment]
@alain27espina There are references to Microsoft.NET.Test.sdk, MSTEST is working, but this is not what I want, I hope to use in resharper

**Comment by Y2zz** [comment]
This problem can exist for so long?
