### ISSUE TITLE
How to exclude tests using dotnet test

### ISSUE THREAD

**Issue by jehof** [machine/machine.specifications#349]
We have decorated some tests with the TagsAttribute to specify them as integration tests

```
[Tags("Integration")]
public class If_this_happens {
  // rest of code
}
```

Now we try to run tests through commandline using `dotnet test` and want to **exclude** the integration tests. Is there a way to provide a parameter to dotnet test to exclude those tests?

We tried the --filter parameter with no success.

**Comment by defiant-v** [comment]
<code>dotnet test --filter ClassName!=Integration.Test.Class.Name -c `Debug</code>

 worked for us!

**Comment by robertcoltheart** [comment]
Duplicate of #327
