### ISSUE TITLE
Is there any plan to support core 2.0?

### ISSUE THREAD

**Issue by Y2zz** [machine/machine.specifications#350]
Currently core2.0 has been released for a long time, MSpec cannot be used normally in core2.0

**Comment by Y2zz** [comment]
@agross @ivanz @dannyvincent

**Comment by jonnii** [comment]
Have you tried? It works fine for me.

**Comment by Y2zz** [comment]
I tried it, is not well supported.

**Comment by BrunoJuchli** [comment]
@Y2zz So what's missing?

**Comment by jonnii** [comment]
You need something like this in your csproj:

```
<PackageReference Include="Machine.Specifications" Version="0.12.0" />
<PackageReference Include="Machine.Specifications.Should" Version="0.11.0" />
<PackageReference Include="Machine.Specifications.Runner.VisualStudio" Version="2.6.1" />
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.6.0" />
```

Then running from `dotnet test` will probably do what you want. I think the bug here is lack of documentation - but that's pretty standard across the board in core land.

**Comment by Y2zz** [comment]
I re-validated that mstest can now be used to run tests but resharper cannot be used to run tests
