### ISSUE TITLE
System.FieldAccessException: Cannot set a constant field

### ISSUE THREAD

**Issue by toebens** [machine/machine.specifications#351]
Hi,
we upgraded our spec project's packages config to use the latest machine specification packages. We had upgraded from:

`  <package id="FakeItEasy" version="1.17.0" targetFramework="net45" />
  <package id="FluentAssertions" version="3.2.1" targetFramework="net45" />
  <package id="Machine.Fakes" version="2.1.0" targetFramework="net45" />
  <package id="Machine.Fakes.FakeItEasy" version="2.1.0" targetFramework="net45" />
  <package id="Machine.Specifications" version="0.9.1" targetFramework="net45" />
  <package id="Machine.Specifications.Should" version="0.8.0-Unstable0007" targetFramework="net45" />
  <package id="RhinoMocks" version="3.6" targetFramework="net45" />`

to:
`  <package id="FakeItEasy" version="4.7.1" targetFramework="net471" />
  <package id="FluentAssertions" version="5.4.1" targetFramework="net471" />
<package id="Machine.Fakes" version="2.9.0" targetFramework="net471" />
  <package id="Machine.Fakes.FakeItEasy" version="2.9.0" targetFramework="net471" />
  <package id="Machine.Specifications" version="0.12.0" targetFramework="net471" />
  <package id="Machine.Specifications.Runner.VisualStudio" version="2.7.0" targetFramework="net471" />
  <package id="Machine.Specifications.Should" version="0.11.0" targetFramework="net471" />
  <package id="Mono.Cecil" version="0.10.0" targetFramework="net471" />
  <package id="RhinoMocks" version="3.6.1" targetFramework="net471" />`

Skipped the packages we did not upgrade. 

Now we are getting tons of messages when running the tests:

`Fatal Error
System.FieldAccessException: Cannot set a constant field.
   at System.Reflection.MdFieldInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture)
   at Machine.Fakes.Sdk.ReflectionExtensions.<>c__DisplayClass7_0.<ResetReferences>b__1(FieldInfo x)
   at Machine.Fakes.Sdk.MissingFrameworkExtensions.Each[T](IEnumerable`1 enumerable, Action`1 action)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Machine.Fakes.Internal.BehaviorConfigController.CleanUp(Object subject)
   at Machine.Fakes.WithFakes`2.<>c.<.ctor>b__1_0()
`

What's wrong? How can i identify where the problem might be? What is causing these exceptions?

Please note that we switched the project from net45 to net 471 some weeks back and hadn't had the problem. We did not update the packages. However i suppose it is some because of the new Machine.Fakes version.
Thanks, toebens

**Comment by robertcoltheart** [comment]
Can you please provide some sample code that reproduces the above?

**Comment by toebens** [comment]
It seems that a public const property within a behavior configuration class is causing these issues. I moved the constant properties to another class then the error is gone.
