### ISSUE TITLE
Test aborted when writing a particular string to console

### ISSUE THREAD

**Issue by mausch** [machine/machine.specifications#359]
This test gets aborted by the test runner, without any explanations (ReSharper 9.0 Update 1):

``` csharp
using System;
using Machine.Specifications;

class Class1
{
    It should_print = () =>
    {
        Console.WriteLine(@"z* B8Ika-r
Vx=3U!f\~J'");
    };
}
```

I've tried the same test with NUnit and it works fine, so the problem is not ReSharper.

In case the copied string is not accurate, I'll dump here the exact bytes:

```
7A 18 2A 20 42 38 04 49 6B 61 2D 72 14 0D 0A 56 78 3D 33 55 21 66 5C 7E 4A 0F 05 27 1D
```

If you're wondering how I got that string, it was generated by FsCheck.

**Comment by robertcoltheart** [comment]
Duplicate of #267
