### ISSUE TITLE
Given classes are not shown in test runner

### ISSUE THREAD

**Issue by chrischu** [machine/machine.specifications#360]
I think it used to be the case that given classes would be represented in the test runner by using a new node ("<SUT>, <when>" > "given" > "it"), but currently that is no longer the case as the given node is not shown at all.

See the following images for an example:

![image](https://cloud.githubusercontent.com/assets/447251/13140842/ab52cd56-d634-11e5-9e69-ec6f424b2489.png)

![image](https://cloud.githubusercontent.com/assets/447251/13140848/b50cb60e-d634-11e5-9001-2b0da2fdf811.png)

**Comment by robertcoltheart** [comment]
Duplicate of #130
