### ISSUE TITLE
Print full usage/options by default

### ISSUE THREAD

**Issue by mausch** [machine/machine.specifications#364]
When I run `mspec.exe` without arguments, I get:

```
Usage: mspec.exe [options] <assemblies>
```

which doesn't tell the user what the options are, or how to get further help. The user either has to guess that `-h`/`--help` is the right option to get the full usage documentation, or else look into the source code to find that out (I did the latter).

I think it would be sensible to show the full usage by default.

**Comment by IndikaUdagedara** [comment]
@robertcoltheart PR #409  pls review
