### ISSUE TITLE
TeamCity 9.0.3, Mspec Latest, times

### ISSUE THREAD

**Issue by mikeblakeuk** [machine/machine.specifications#369]
Hi,

Please could provide details of the best way to run our MSpec dll (.net 4.0) in Team City.
Ideally, we want to see the time it takes to run the tests (not just the Behaviours/It commands). Our workaround is to console stopwatch times. Can we use --html and --time?

Should we use the Team City step or PowerShell?

Note; we use ReSharper 9.1

Thanks

**Comment by robertcoltheart** [comment]
For now, using the package `TeamCity.VSTest.TestAdapter` will report timings to TeamCity.
