### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by fcallejon** [machine/machine.specifications#374]
Is the nuget package up to date?

**Comment by robertcoltheart** [comment]
Not sure I understand, what are you missing? The nuget package is up to date with the code in this repo. yes.

**Comment by fcallejon** [comment]
The nuget page says:
> last updated 10/11/2017

**Comment by robertcoltheart** [comment]
Correct, this matches with our release page: https://github.com/machine/machine.specifications/releases
