### ISSUE TITLE
Annotations no longer working in R#

### ISSUE THREAD

**Issue by ajj7060** [machine/machine.specifications#382]
Using the latest MSpec + R# (2019.1.0 and 2019.1.1) in VS 2019, the annotations don't appear to be working and R# says Establish, Because and It delegates are not used and can be removed.

If you open the Annotations settings in R#, it looks like they are still there, but if you clear the checkbox and Save the changes, when you come back they are gone from the custom annotations list.

Let me know if there's somehow more information I can gather.

**Comment by robertcoltheart** [comment]
Thanks for the report, I'll take a look but I might not get to this until next week.

**Comment by robertcoltheart** [comment]
I've looked into this, I don't think it's R# that's causing the issue, it seems like it's actually VS 2019 that is overwriting R# settings in terms of implicit usage. Nothing has changed in MSpec for annotations, so not sure what is going on.

**Comment by robertcoltheart** [comment]
Just to add to this, you know that the annotations only worked if you had a subject attribute on your class, right? It won't work if there is no subject.

**Comment by robertcoltheart** [comment]
I'm going to close this, as this appears to be either a VS or R# issue and not MSpec.

![image](https://user-images.githubusercontent.com/13191652/58549164-7dff2580-823d-11e9-8237-43558455bb1f.png)

**Comment by ajj7060** [comment]
yes, I know the annotations only works with a subject; it used to gray everything out until a Subject attribute was added somewhere.

Are you sure this isn't an mspec thing, because the namespace used to show in the Code Annotations settings in R#, and they don't anymore.  When it showed, if you didn't check the checkbox for Machine.Specifications, it wouldn't use them either.

![MSpecAnnotations](https://user-images.githubusercontent.com/1903891/58578171-23060800-8216-11e9-929b-0e64726763c0.png)

**Comment by robertcoltheart** [comment]
I suspect R# have changed the way the annotations propagate up to the settings UI, there's nothing that's changed in MSpec that would have affected this.

**Comment by ajj7060** [comment]
I don't think its just a UI thing; clearly R# isn't recognizing the annotations for mspec anymore.  Is this not the right place for issues related to mspec R# integration?

**Comment by robertcoltheart** [comment]
Consider the following cases:

## 1
No attributes or annotations
![image](https://user-images.githubusercontent.com/13191652/58748787-14d31880-84b0-11e9-9f47-afda1986009d.png)

R# reports the field as unused and text coloring shows as unused:
![image](https://user-images.githubusercontent.com/13191652/58748802-346a4100-84b0-11e9-9dfe-a910e26fa18b.png)

## 2
With subject
![image](https://user-images.githubusercontent.com/13191652/58748850-ab9fd500-84b0-11e9-9595-9181221fd587.png)

R# no longer reports as unused, but text coloring still indicates unused.
![image](https://user-images.githubusercontent.com/13191652/58748856-c114ff00-84b0-11e9-9480-a53d55e2995a.png)

If you add a public modifier, the text coloring changes to used, which indicates that either R# or the Roslyn analyzer is automatically treating private fields as unused.
![image](https://user-images.githubusercontent.com/13191652/58748881-236dff80-84b1-11e9-82fb-51bcf604e6e8.png)

## 3
With normal R# annotations
![image](https://user-images.githubusercontent.com/13191652/58748912-c0309d00-84b1-11e9-848f-43ab439f2f4c.png)

R# doesn't report as unused, text coloring indicates unused, same as in case 2.
![image](https://user-images.githubusercontent.com/13191652/58748921-db9ba800-84b1-11e9-944f-3558daacafcd.png)

Adding a public modifier exhibits the same behavior as in case 2.
![image](https://user-images.githubusercontent.com/13191652/58748923-ea825a80-84b1-11e9-9492-e84d31797538.png)

I hope that's comprehensive enough for you. Bottom line, you won't get warnings in your build if you are running R# analyzers, but the text coloring appears to be off. I'd suggest raising a ticket over at https://youtrack.jetbrains.com if it still bothers you. An alternative is to implement project-level settings using R# settings layers, and fix it that way.
