### ISSUE TITLE
Is there a Road Map?

### ISSUE THREAD

**Issue by mikeblakeuk** [machine/machine.specifications#389]
Hi,
Is there a road map with some timescales for MSpec?
We want to improve the DevOps (VSTS / VS) adapter (e.g. support tags, make the test into a hierarchy, record total times etc )
We don't want to write this if the code base is "moving" soon.
Do you have any idea one when 2.0 will be due. we would love to help beta test it.
Thanks

@robertcoltheart / @ivanz

**Comment by robertcoltheart** [comment]
Yep, take a look at: https://github.com/machine/machine.specifications/milestone/11 which is the road to 2.0.

Also, from memory and in no particular order:

1. Remove all remoting code and use the reflection runners
2. Move runner code to the runner utility package and also make it a bit more forward compatible, something like xUnit's `ITestFramework` class in the abstractions package.
3. Refactor the adapter to be backwards/forwards compatible and use the new infrastructure
4. Lots of bug fixes and enhancements like a proper CI reporter to integrate with Teamcity, Appveyor etc.
5. Dropping support for older EOL frameworks

I'm still formulating in my head what needs to be done to modernise the framework, so some of this is still in the planning stage. I don't have a date when all this will be ready to beta test, but let's assume not for a while yet 🙁.

**Comment by mikeblakeuk** [comment]
Any news on this?
"No due date 0% complete"

**Comment by robertcoltheart** [comment]
Nothing to report as yet, I've finished consolidating repos and have a plan for how to move forward. Have been pulled away onto other things for a bit, will return to this as soon as I can.
