### ISSUE TITLE
Add support for custom test events

### ISSUE THREAD

**Issue by mikeblakeuk** [machine/machine.specifications#406]
We want to Add Azure App Insights to the test to monitor performance.
Can we add a `ITestContext` that works in the same way as `IAssemblyContext` (like IOutput)?

This feels the wrong way of doing it:
https://github.com/machine/machine.specifications/compare/master...mikeblakeuk:task/appinsights-timer

**Comment by robertcoltheart** [comment]
Bottom line: there isn't any real reporting for all the major CI tools nor extensible reporting hooks. This is very much a `2.0` thing and covered here: #366. If you want to output test execution (for now), I'm afraid you're stuck with what you've done in your code above. I can revisit when I get more time after the current quarantine.

**Comment by mikeblakeuk** [comment]
Now we can use the Visual Studio TestAdapter, Azure DevOps reporting comes out for "free". (just run dotnet test). It more about adding extension points so we can do actions before / after tests, (both subjects, establish, because, it etc).

Looks like we need to push hard to upgrade from .net 4.5.2 so we can use 2.0. It might be we jump to .net 5.0 due in October..

My other main concern is the use of the word "current" re; quarantine!
