### ISSUE TITLE
Automatically suggest plugin in Rider

### ISSUE THREAD

**Issue by van800** [machine/machine.specifications#410]
Starting with Rider 2020.2 EAP2 there is a way to automatically suggest plugin, when it has certain reference, like "Machine.Specifications" in this case.

If you want plugin to be automatically suggested, please  contact JetBrains support and ask to add a plugin Feature
`com.jetbrains.rider.solution.reference`
with value 
`Machine.Specifications`.

Resulting dialog would look like this one: https://twitter.com/IvanShakhov/status/1270604533660626944

Ping me here in comments in case of any questions.

**Comment by robertcoltheart** [comment]
Noted, will look into adding it.

**Comment by van800** [comment]
If you agree, I can facilitate it.

**Comment by robertcoltheart** [comment]
Ah thanks, I submitted a support request as well.

**Comment by van800** [comment]
Association for the plugin was added. It can't be really checked right now because there is no 2020.2 version of the plugin yet.

**Comment by robertcoltheart** [comment]
Thanks, I'll close this for now and re-open if there are issues post 2020.2.
