### ISSUE TITLE
R# Console output not displayed

### ISSUE THREAD

**Issue by derekgreer** [machine/machine.specifications#420]
I'm using Machine.Specifications version 1.0.0 with Visual Studio 2019 and  JetBrains ReSharper 2020.2.3 Build 202.0.20200915.120740 built on 2020-09-15 ReSharper 2020.2.20200917.63436. 

I'm trying to place Console.WriteLine() statements, but don't see them output anywhere.  I'd expect them to be in the R# output window, or perhaps the Visual Studio Output window for "Tests" but it doesn't appear.  I saw an old issue on this.  Should this be working currently?

**Comment by robertcoltheart** [comment]
Correct, Console.WriteLine statements will not output the text anywhere. This is slated for version 2.0 as detailed in #324, as it will require a mechanism similar to xUnit: https://xunit.net/docs/capturing-output
