### ISSUE TITLE
1.1.0-beta2 on Nuget does not match repo

### ISSUE THREAD

**Issue by neilrees** [machine/machine.specifications#435]
The nuget of 1.1.0-beta.2 on nuget https://www.nuget.org/packages/Machine.Specifications/1.1.0-beta.2 does not contain the beta2 code from this repository.

nuget.org version of 1.1.0-beta.2 is dated 10th February 2021
Github release of 1.1.0-beta.2 was released 24th April 2021

nuget.org beta.2 does not contain the performance fixes from https://github.com/machine/machine.specifications/pull/433

e.g. Disassembling machine.specification.dll with dotPeek downloaded from nuget.org, contains code that was deleted by the PR:
![image](https://user-images.githubusercontent.com/282424/117134362-6459a780-ad9d-11eb-8725-94302f366fac.png)

**Comment by robertcoltheart** [comment]
Apologies, I have pushed this out as `v1.1.0-beta.3`.
