### ISSUE TITLE
Please add support for R# 2022.3

### ISSUE THREAD

**Issue by mikeblakeuk** [machine/machine.specifications#488]
Standard stuff

I tried to do it but wasn't sure about the IPsiSourceFile PsiSourceFile change

https://github.com/machine/machine.specifications.runner.resharper/compare/master...mikeblakeuk:machine.specifications.runner.resharper:task/2022_3

@robertcoltheart

**Comment by robertcoltheart** [comment]
Released, please allow a few days for JetBrains to approve.
