### ISSUE TITLE
Add support for R# 2024.2

### ISSUE THREAD

**Issue by mikeblakeuk** [machine/machine.specifications#526]
Please add support for 2024.2
![image](https://github.com/user-attachments/assets/e89c54e7-9320-49fa-bae2-19e255a7d27d)

JetBrains ReSharper 2024.2.3
Build 242.0.20240829.213636 built on 2024-08-29
dotTrace 2024.2.20240829.213636
ReSharper 2024.2.20240829.213636
AI Assistant 2024.2.20240829.213636
Machine.Specifications.Runner.Resharper9.2024.1.0 package not installed (Incompatible)

**Comment by robertcoltheart** [comment]
Fixed in https://github.com/machine/machine.specifications.runner.resharper/pull/339
