### ISSUE TITLE
Support for Rider 2024.3

### ISSUE THREAD

**Issue by jhickson** [machine/machine.specifications#531]
Hi,

The current version of the Rider plugin is incompatible with Rider 2024.3. Could the plugin be updated, please?

**Comment by robertcoltheart** [comment]
This is released. 

But FYI I'm likely going to put Rider/R# support in the fridge. The JetBrains API changes are killing me. For comparison's sake, I've not had to update the Visual Studio runner _in years_, whereas the JB API makes _significant_ breaking changes with each release, none of which are even remotely documented and are only untangled by decompiling JB's assemblies.

The MSpec plugin gets more and more broken with each release, and without some significant support, or JetBrains themselves taking it over, I'm done.

Feel free to fork it at this point if you'd like to see continued support.

**Comment by jhickson** [comment]
Hi @robertcoltheart ,

Many thanks for adding the support. Having only recently started  using MSpec, I didn't realise maintaining the plugin took so much work and can totally understand why you are considering freezing support.

**Comment by Slesa** [comment]
From me also many thanks. I really don't understand Jetbrains position here. For every new version of their IDEs I have to wait at least a month or two until every used plugin is updated. What is this good for?

**Comment by neilrees** [comment]
@hhariri Is this something you could feedback to the R# team?  How about first party support within Rider?
