### ISSUE TITLE
TeamCity reports "Property value not found" when an exception is thrown

### ISSUE THREAD

**Issue by rlipscombe** [machine/machine.specifications#72]
In my TeamCity logs, I see the following:

```
[10:06:27]: [Step 2/4] ##teamcity[message test='Exception has been thrown by the target of an invocation.'
    errorDetails='<exception details and stack trace goes here>' status='ERROR'']
[10:06:28]: [Step 2/4] Property value not found
Valid property list format is (name( )*=( )*'escaped_value'( )*)* where escape simbol is "|"
```

I _think_ that this is because of the spurious extra single quote at the end (`'']`)

It looks like it's added (unconditionally) by TeamCityErrorMessageWriter.WriteError, at line 245 or so.

**Comment by sandipgudmewar** [comment]
I have facing the issue at execution of job in team city it shows the following error message " Incorrect property name.Valid property list format is (name( )*=( )*'escaped_value'( )*)* where escape symbol is "|" "

Please suggest me the solution and steps where we need to update the setting.
